/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/auth/Login': RouteRecordInfo<'/auth/Login', '/auth/Login', Record<never, never>, Record<never, never>>,
    '/auth/Register': RouteRecordInfo<'/auth/Register', '/auth/Register', Record<never, never>, Record<never, never>>,
    '/profile/Profile': RouteRecordInfo<'/profile/Profile', '/profile/Profile', Record<never, never>, Record<never, never>>,
    '/table/Products': RouteRecordInfo<'/table/Products', '/table/Products', Record<never, never>, Record<never, never>>,
    '/table/Table': RouteRecordInfo<'/table/Table', '/table/Table', Record<never, never>, Record<never, never>>,
  }
}
